app.media.max-video-size=10MB
app.media.max-image-per-product=20
app.media.max-video-per-product=3
app.media.max_image_size=10MB
app.media.presigned.upload-ttl=5m
app.media.presigned.view-ttl=1d

app.media.temp.bucket-size=10m
app.media.temp.cleanup-interval=16m