spring.application.name=dutch
spring.datasource.url=jdbc:postgresql://localhost:5432/dutch_auction_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=
