spring.application.name=dutch
spring.datasource.url=jdbc:postgresql://localhost:5432/dutch_auction_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=

#Object data
minio.url=http://localhost:9000
minio.access-key=
minio.secret-key=

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=


app.media.cleanup-interval-ms=600000
